#!/usr/bin/env bash
# displays a list of currently running processes
# Display in a user-oriented format
# Must show all processes, for all users,
#  including those which might not have a TTY
# Show process hierarchy

ps -auxf
