#!/usr/bin/env bash
# nginx must be running as nginx use

sudo pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sed -i "1 i user nginx;" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart