#!/usr/bin/env bash
# make your fix short and sweet.

sudo pkill apache2
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart